spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xunyou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
    timeout: 0
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:Mapping/*Mapping.xml
  type-aliases-package: com.example.xunyou.mapper



